### ISSUE TITLE
Tabslider

### ISSUE THREAD

**Issue by weiyideai520** [alexyle/jellyfin-theme#2]
Tabslider covers the title.

![1711077120755](https://github.com/alexyle/jellyfin-theme/assets/2784569/8f38db9b-e0df-4cd5-a87e-07b7cb03e936)

**Comment by alexyle** [comment]
yes it glassmorphisme

**Comment by alexyle** [comment]
Ok I see I check

**Comment by alexyle** [comment]
it good
